# Generated by Django 4.1.7 on 2023-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipeimages/default.png', upload_to='recipeimages/'),
        ),
    ]
